// Generated by CoffeeScript 1.4.0
(function() {

  window.config = {
    user: "acetous",
    links: [
      {
        description: "Twitter",
        icon: "icon-twitter",
        url: "https://twitter.com/acetous"
      }, {
        description: "Blog",
        icon: "icon-user",
        url: "http://www.acetous.de/"
      }
    ],
    languages: {
      'js': 'JavaScript',
      'rb': 'Ruby'
    }
  };

}).call(this);
